db:
  image: postgres
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
odoo:
  image: odoo
  #It doesn't support --x-networking option yet
  links:
    - db:db
  ports:
    - 8069:8069
